export function getDomRefs(doc = document) {
  const boothActionMenu = doc.getElementById('boothActionMenu');
  return {
    app: doc.getElementById('app'),
    bottomDrawer: doc.getElementById('bottomDrawer'),
    drawerPeek: doc.getElementById('drawerPeek'),
    drawerTitle: doc.getElementById('drawerTitle'),
    drawerSummaryText: doc.getElementById('drawerSummaryText'),
    drawerPrimaryCount: doc.getElementById('drawerPrimaryCount'),
    drawerSecondaryCount: doc.getElementById('drawerSecondaryCount'),
    drawerPrimaryList: doc.getElementById('drawerPrimaryList'),
    drawerSecondaryList: doc.getElementById('drawerSecondaryList'),
    drawerShareBtn: doc.getElementById('drawerShareBtn'),
    drawerClearBtn: doc.getElementById('drawerClearBtn'),
    topViewBtn: doc.getElementById('topViewBtn'),
    resetViewBtn: doc.getElementById('resetViewBtn'),
    hallModelBtn: doc.getElementById('hallModelBtn'),
    categoryLayerBtn: doc.getElementById('categoryLayerBtn'),
    themeToggleBtn: doc.getElementById('themeToggleBtn'),
    categoryLegend: doc.getElementById('categoryLegend'),
    categoryLegendList: doc.getElementById('categoryLegendList'),
    boothSearchInput: doc.getElementById('boothSearchInput'),
    boothSearchClearBtn: doc.getElementById('boothSearchClear'),
    boothSearchMeta: doc.getElementById('boothSearchMeta'),
    boothSearchCount: doc.getElementById('boothSearchCount'),
    boothSearchResults: doc.getElementById('boothSearchResults'),
    boothSearchResultsList: doc.getElementById('boothSearchResultsList'),
    placeholder: doc.getElementById('placeholder'),
    detail: doc.getElementById('detail'),
    boothIdEl: doc.getElementById('boothId'),
    boothNameEl: doc.getElementById('boothName'),
    boothMetaEl: doc.getElementById('boothMeta'),
    boothDescEl: doc.getElementById('boothDesc'),
    selectionBadge: doc.getElementById('selectionBadge'),
    linkRow: doc.getElementById('linkRow'),
    markPrimaryBtn: doc.getElementById('markPrimaryBtn'),
    markSecondaryBtn: doc.getElementById('markSecondaryBtn'),
    toast: doc.getElementById('toast'),
    errorBox: doc.getElementById('errorBox'),
    boothActionMenu,
    menuBoothId: doc.getElementById('menuBoothId'),
    menuNodes: boothActionMenu ? Array.from(boothActionMenu.querySelectorAll('.action-node')) : [],
    labelCanvas: doc.getElementById('labelCanvas'),
  };
}
